@startuml Classe Barra

class Barra {
    - _caminho: str
    + id: str
    + nome: str
    + nivel_de_tensao: str
    + dados: pd.DataFrame
    + potencia_limite: float
    + ler_csv(_file_name: str): pd.DataFrame
    + calcular_mst_operacional(potencia_ponto_de_operacao: float): float
    + __repr__(): str
}

@enduml  